version: 2
jobs:
  go-lint:
    docker:
    - image: circleci/golang:1.11.5

    working_directory: /go/src/github.com/mf-financial/cayenne-wallet-util
    steps:
    - checkout
    - run: git branch -u origin/${CIRCLE_BRANCH}
    - run: go get -u -d -t -v ./...
    - run: go get -u github.com/client9/misspell/cmd/misspell
    - run: go get -u github.com/gordonklaus/ineffassign
    - run: go get github.com/securego/gosec/cmd/gosec/...
    - run: go vet `go list ./... | grep -v "/vendor/"`
    - run: misspell `find . -name "*.go" | grep -v "/vendor/"`
    - run: ineffassign .
    - run: gosec ./...
    - run: go test -v ./...
workflows:
  version: 2
  build:
    jobs:
    - go-lint:
        filters:
          branches:
            only: /.*/
